import { Router } from 'express';
// ...existing code...
import { audit } from '../audit/audit.service.js';
// ...existing code...
router.post('/:id/archive', authMiddleware, async (req, res) => {
  // ...existing code...
    await audit(userId, 'listing', listing.id, 'ARCHIVE');
  // ...existing code...
});

